version: '3'

networks:
  react_express:
    driver: bridge

services:
  frontend:  # React用のコンテナ
    build: .
    container_name: front_hack
    tty: true
    volumes:
      - ../front:/frontend
    working_dir: "/front"
    ports:
      - 3001:3000
    networks:
      - react_express
  backend:  # Express用のコンテナ
    build: .
    container_name: back_hack
    tty: true
    volumes:
      - ../back:/backend
    working_dir: "/back"
    ports:
      - 3002:3000
    networks:
      - react_express
