version: '3'

networks:
  react_express:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root       # 任意のユーザー名
      POSTGRES_PASSWORD: secret_pass   # 任意のパスワード
      POSTGRES_DB: oshiohaka         # 任意のデータベース名
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:  # React用のコンテナ
    build: .
    container_name: front_hack
    tty: true
    volumes:
      - ../front:/frontend
    working_dir: "/front"
    ports:
      - 3001:3000
    networks:
      - react_express
  backend:  # Express用のコンテナ
    build: .
    container_name: back_hack
    tty: true
    volumes:
      - ../back:/backend
    working_dir: "/back"
    ports:
      - 3002:3000
    networks:
      - react_express

volumes:
  postgres_data:
