FROM node:14
# # フロントエンドのDockerfile
# FROM node:16

# WORKDIR /workspace/backend

# # 依存関係のインストール
# # COPY ../back/ ./
# COPY package.json ./
# COPY package-lock.json ./
# RUN npm install

# # アプリケーションのコードをコピー
# # COPY . .

# # アプリケーションをビルド
# RUN npm run build

# # アプリケーションを起動
# # CMD ["npm", "start"]

# # アプリケーションを起動 あっているか微妙
# CMD ["npm", "run", "dev"]
# # CMD ["node", "index.js"]  # Honoのエントリーポイントを指定